### ISSUE TITLE
Special whitespace not supported ?

### ISSUE THREAD

**Issue by Stepland** [Stepland/jubeatools#9]
The example file in #8 also triggers another bug

```py3
Traceback (most recent call last):
  File "c:\users\nomlas\appdata\local\programs\python\python39\lib\site-packages\jubeatools\formats\jubeat_analyser\memo2\load.py", line 429, in _load_memo2_file
    parser.load_line(raw_line)
  File "c:\users\nomlas\appdata\local\programs\python\python39\lib\site-packages\jubeatools\formats\jubeat_analyser\memo2\load.py", line 321, in load_line
    raise SyntaxError(f"not a valid memo2 file line : {line}")
SyntaxError: not a valid memo2 file line : □□①□　　　|①−−−|

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nomlas\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\nomlas\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Nomlas\AppData\Local\Programs\Python\Python39\Scripts\jubeatools.exe\__main__.py", line 7, in <module>
  File "c:\users\nomlas\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\nomlas\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\nomlas\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\nomlas\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\nomlas\appdata\local\programs\python\python39\lib\site-packages\jubeatools\cli\cli.py", line 71, in convert
    song = loader(Path(src), **loader_options)
  File "c:\users\nomlas\appdata\local\programs\python\python39\lib\site-packages\jubeatools\formats\jubeat_analyser\memo2\load.py", line 462, in load_memo2
    charts = [_load_memo2_file(lines) for _, lines in files.items()]
  File "c:\users\nomlas\appdata\local\programs\python\python39\lib\site-packages\jubeatools\formats\jubeat_analyser\memo2\load.py", line 462, in <listcomp>
    charts = [_load_memo2_file(lines) for _, lines in files.items()]
  File "c:\users\nomlas\appdata\local\programs\python\python39\lib\site-packages\jubeatools\formats\jubeat_analyser\memo2\load.py", line 431, in _load_memo2_file
    raise SyntaxError(f"On line {i}\n{e}")
SyntaxError: On line 8
not a valid memo2 file line : □□①□　　　|①−−−|
```

**Comment by Stepland** [comment]
According to the person who found the bug, this was fixed by changing the whitespace between the position and timing parts, so I suspect some unusual whitespace character ?

**Comment by Stepland** [comment]
The file was using U+3000 (Ideographic space), which is hardly surprising in japanese text files but wasn't accepted as whitespace by the parsing code
